name: lint
on: [push]
jobs:
  install-lint:
    runs-on: ubuntu-latest
    steps:
      - name: récupération du repo
        uses: actions/checkout@v4
      - name: install python 
        uses: actions/setup-python@v5
      - name: install des deps
        run: |
          pip install --quiet --upgrade --requirement requirements.txt
      - name: install flake8 & pylint
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --errors-only --disable=C0301 --disable=C0326 *.py
      - name: unitest
        run: |
          python -m unittest --verbose --failfast